app:
  image: 
    repository: fabricio07/ukiyo-api-gateway
    tag: latest
    pullPolicy: Always
  containerPort: 3000
  container:
    name: ukiyo-api-gateway
    Port: 3000
    replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ukiyocazorla.es
  path: /
  pathType: Prefix