{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: {{ .Values.app.containerPort | quote }}
  DATABASE_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.app.name }}-postgres:{{ .Values.postgres.port }}/{{ .Values.postgres.db }}"
  NATS_SERVERS: {{ .Values.global.nats.url | quote }}
  REPO_GIT: {{ .Values.global.env.REPO_GIT | quote }}
{{- end }}