jenkins:
  controller:
    componentName: "jenkins-controller"
    jenkinsUrl: "http://jenkins-bmleon.ukiyocazorla.es"
    
    # CAMBIO CRÍTICO: Ejecutar como root para acceder al socket de Docker (/var/run/docker.sock)
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 0
    
    admin:
      username: "admin"
      password: "admin123"
    
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1536Mi"
    
    persistence:
      enabled: true
      storageClass: "microk8s-hostpath"
      size: "8Gi"
    
    serviceType: ClusterIP
    
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostName: "jenkins-bmleon.ukiyocazorla.es"
      path: "/"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        kubernetes.io/ingress.class: "nginx"
    
    installPlugins:
      - kubernetes:4306.vc91e951ea_eb_d
      - workflow-aggregator:600.vb_57cdd26fdd7
      - git:5.7.0
      - docker-workflow:585.va_0768b_843e93
      - configuration-as-code:2006.v001a_2ca_6b_574
    
    installLatestPlugins: false
    javaOpts: "-Djava.net.preferIPv4Stack=true"
    
    sidecars:
      configAutoReload:
        enabled: false

  agent:
    enabled: true
    # Los agentes también deben poder correr procesos si los usaras en el futuro
    runAsUser: 0
    runAsGroup: 0