jenkins:
  controller:
    componentName: "jenkins-controller"
    jenkinsUrl: "http://jenkins-bmleon.ukiyocazorla.es"
    
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    
    admin:
      username: "admin"
      password: "admin123"
    
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1536Mi"
    
    persistence:
      enabled: true
      storageClass: "microk8s-hostpath"
      size: "8Gi"
    
    # --- Conexión física con Docker del servidor VPS ---
    volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
      - name: docker-bin
        hostPath:
          path: /usr/bin/docker
          
    volumeMounts:
      - name: docker-sock
        mountPath: /var/run/docker.sock
      - name: docker-bin
        mountPath: /usr/bin/docker
    # ---------------------------------------------------
    
    serviceType: ClusterIP
    
    ingress:
      enabled: true
      ingressClassName: "nginx"
      hostName: "jenkins-bmleon.ukiyocazorla.es"
      path: "/"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        kubernetes.io/ingress.class: "nginx"
    
    installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - docker-workflow
    
    installLatestPlugins: false
    javaOpts: "-Djava.net.preferIPv4Stack=true"
    
    JCasC:
      enabled: false
    sidecars:
      configAutoReload:
        enabled: false

  agent:
    enabled: true
    runAsUser: 1000
    runAsGroup: 1000