apiVersion: v1
kind: Service
metadata:
  name: {{ include "infra-nats.fullname" . | default "infra-nats" }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 4222
      protocol: TCP
      name: nats
  selector:
    app: nats