apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: infra-nats
spec:
  selector:
    matchLabels:
      app: nats
  serviceName: "infra-nats"
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 4222
          name: nats