apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: combined-ingress
  annotations:
    # Quitamos la anotación de ingress.class para evitar el warning
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  # Esta es la línea clave que debe sustituir a la anotación
  ingressClassName: public 
  rules:
  - host: jenkins-bmleon.ukiyocazorla.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jenkins
            port:
              number: 8080
  - host: admin-ukiyo.ukiyocazorla.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ukiyo-admin-service
            port:
              number: 80